name: contacts_app_server
description: A simple command-line application.
environment: 
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  mongo_dart: ^0.5.0+1
  sevr: ^1.0.4
  
dev_dependencies: 
  pedantic: ^1.9.0
